[package]
name = "gmail-filters-rs"
version = "0.1.0"
edition = "2021"
license = "WTFPL"

[dependencies]
aho-corasick = "1.1.3"
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.216", features = ["serde_derive"] }
toml = "0.8.19"
